### ISSUE TITLE
data for assessment ipynb?

### ISSUE THREAD

**Issue by dpellow** [fmaguire/MAG_gi_plasmid_analysis#14]
Is the raw data for running the ipynb available somewhere, or do I need to rerun the read simulation and all the assemblers and binners from scratch?

**Comment by fmaguire** [comment]
Unfortunately OSF is limited to 5GB a file so I couldn't upload the raw simulated reads.

I'm currently running the uploading the raw reads to figshare as I can link that into the OSF project. I'll post a link here when its done uploading.

The documentation could do with some tidying here too.

**Comment by dpellow** [comment]
Thanks!
I'm not sure the raw reads are needed, but some of the files to run the ipynb seem to be missing.
I would also be really interested in seeing a mapping of individual reference plasmids to their bins beyond just the aggregate statistics.
(Maybe tables with all the chromosomes / plasmids / gis / genes as rows and then for each assembler-binner combination columns for whether or not they were assembled / binned / correctly binned and which bin number(s) it is in - do you have that information available somewhere?)

**Comment by fmaguire** [comment]
This tarball should contain all the intermediate data/files needed to execute the notebook without rebuilding them using the runscripts: https://osf.io/8tzjk/

**Comment by dpellow** [comment]
Thanks!

**Comment by fmaguire** [comment]
Sorry I don't have more time to generate the data table.  Let me know if you have any issues.

I did start looking into using SCAPP (among other plasmid focused assemblers) to reduce the assembly related plasmid loss, and it definitely improved things a bit.  However, binning was still the main problem area for losing MGEs and wanted to keep the main story as clear as possible!
